version: '3.8'

services:
  parent-portal:
    build: .
    ports:
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

